version: '3'

services:
  model:
    container_name: spotlight_model
    build: .
    volumes:
    - .:/app
    environment:
      FLASK_ENV: development
    env_file:
    - .env
    ports:
    - '5001:5001'